### ISSUE TITLE
`npm install -g triton` broken?

### ISSUE THREAD

**Issue by smartb-pair** [TritonDataCenter/triton#237]
[2017-09-07T12_04_02_966Z-debug.log.zip](https://github.com/joyent/triton/files/1284585/2017-09-07T12_04_02_966Z-debug.log.zip)
On macOS 10.12.6 we see:
```
$ sudo npm install -g triton
npm WARN deprecated node-uuid@1.4.8: Use uuid module instead
/usr/local/bin/triton -> /usr/local/lib/node_modules/triton/bin/triton

> dtrace-provider@0.6.0 install /usr/local/lib/node_modules/triton/node_modules/dtrace-provider
> node scripts/install.js

fs.js:772
  return binding.rename(pathModule._makeLong(oldPath),
                 ^

Error: EACCES: permission denied, rename '/usr/local/lib/node_modules/triton/node_modules/dtrace-provider/compile.py' -> '/usr/local/lib/node_modules/triton/node_modules/dtrace-provider/binding.gyp'
    at Object.fs.renameSync (fs.js:772:18)
    at Object.<anonymous> (/usr/local/lib/node_modules/triton/node_modules/dtrace-provider/scripts/install.js:14:4)
    at Module._compile (module.js:573:30)
    at Object.Module._extensions..js (module.js:584:10)
    at Module.load (module.js:507:32)
    at tryModuleLoad (module.js:470:12)
    at Function.Module._load (module.js:462:3)
    at Function.Module.runMain (module.js:609:10)
    at startup (bootstrap_node.js:158:16)
    at bootstrap_node.js:598:3

> dtrace-provider@0.8.5 install /usr/local/lib/node_modules/triton/node_modules/mooremachine/node_modules/dtrace-provider
> node scripts/install.js

fs.js:772
  return binding.rename(pathModule._makeLong(oldPath),
                 ^

Error: EACCES: permission denied, rename '/usr/local/lib/node_modules/triton/node_modules/mooremachine/node_modules/dtrace-provider/compile.py' -> '/usr/local/lib/node_modules/triton/node_modules/mooremachine/node_modules/dtrace-provider/binding.gyp'
    at Object.fs.renameSync (fs.js:772:18)
    at Object.<anonymous> (/usr/local/lib/node_modules/triton/node_modules/mooremachine/node_modules/dtrace-provider/scripts/install.js:14:4)
    at Module._compile (module.js:573:30)
    at Object.Module._extensions..js (module.js:584:10)
    at Module.load (module.js:507:32)
    at tryModuleLoad (module.js:470:12)
    at Function.Module._load (module.js:462:3)
    at Function.Module.runMain (module.js:609:10)
    at startup (bootstrap_node.js:158:16)
    at bootstrap_node.js:598:3

> dtrace-provider@0.8.5 install /usr/local/lib/node_modules/triton/node_modules/restify-clients/node_modules/bunyan/node_modules/dtrace-provider
> node scripts/install.js

fs.js:772
  return binding.rename(pathModule._makeLong(oldPath),
                 ^

Error: EACCES: permission denied, rename '/usr/local/lib/node_modules/triton/node_modules/restify-clients/node_modules/bunyan/node_modules/dtrace-provider/compile.py' -> '/usr/local/lib/node_modules/triton/node_modules/restify-clients/node_modules/bunyan/node_modules/dtrace-provider/binding.gyp'
    at Object.fs.renameSync (fs.js:772:18)
    at Object.<anonymous> (/usr/local/lib/node_modules/triton/node_modules/restify-clients/node_modules/bunyan/node_modules/dtrace-provider/scripts/install.js:14:4)
    at Module._compile (module.js:573:30)
    at Object.Module._extensions..js (module.js:584:10)
    at Module.load (module.js:507:32)
    at tryModuleLoad (module.js:470:12)
    at Function.Module._load (module.js:462:3)
    at Function.Module.runMain (module.js:609:10)
    at startup (bootstrap_node.js:158:16)
    at bootstrap_node.js:598:3

> dtrace-provider@0.7.1 install /usr/local/lib/node_modules/triton/node_modules/restify-clients/node_modules/dtrace-provider
> node scripts/install.js

fs.js:772
  return binding.rename(pathModule._makeLong(oldPath),
                 ^

Error: EACCES: permission denied, rename '/usr/local/lib/node_modules/triton/node_modules/restify-clients/node_modules/dtrace-provider/compile.py' -> '/usr/local/lib/node_modules/triton/node_modules/restify-clients/node_modules/dtrace-provider/binding.gyp'
    at Object.fs.renameSync (fs.js:772:18)
    at Object.<anonymous> (/usr/local/lib/node_modules/triton/node_modules/restify-clients/node_modules/dtrace-provider/scripts/install.js:14:4)
    at Module._compile (module.js:573:30)
    at Object.Module._extensions..js (module.js:584:10)
    at Module.load (module.js:507:32)
    at tryModuleLoad (module.js:470:12)
    at Function.Module._load (module.js:462:3)
    at Function.Module.runMain (module.js:609:10)
    at startup (bootstrap_node.js:158:16)
    at bootstrap_node.js:598:3
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: dtrace-provider@0.6.0 (node_modules/triton/node_modules/dtrace-provider):
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: dtrace-provider@0.6.0 install: `node scripts/install.js`
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: Exit status 1
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: dtrace-provider@0.8.5 (node_modules/triton/node_modules/mooremachine/node_modules/dtrace-provider):
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: dtrace-provider@0.8.5 install: `node scripts/install.js`
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: Exit status 1
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: dtrace-provider@0.8.5 (node_modules/triton/node_modules/restify-clients/node_modules/bunyan/node_modules/dtrace-provider):
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: dtrace-provider@0.8.5 install: `node scripts/install.js`
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: Exit status 1

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! dtrace-provider@0.7.1 install: `node scripts/install.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the dtrace-provider@0.7.1 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/smartb/.npm/_logs/2017-09-07T12_04_02_966Z-debug.log
```
Logfile is attached.

**Comment by smartb-pair** [comment]
Running `npm config set unsafe-perm true` seems to be a valid workaround...

**Comment by bahamat** [comment]
Closing as per reporter.
